# docs
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "quarterly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "quarterly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
