// ॥ श्री गणेशाय नमः ॥ 

const tokenList = {
	"PLUS": (input) => input == '+',
	"MINUS": (input) => input == '-',
	"DIVIDE": (input) => input == '/',
	"MULTIPLY": (input) => input == '*',
	"MODULO": (input) => input == '%',
	"EQUALS": (input) => input == '=',
	"GREATERTHAN": (input) => input == '>',
	"LESSTHAN": (input) => input == '<',
	"NOT": (input) => input == '!',
	"GREATERTHANEQUAL": (input) => input == '>=',
	"LESSTHANEQUAL": (input) => input == '<=',
	"NOTEQUALTO": (input) => input == '!=',
	"EQUALTO": (input) => input == '==',
	"FATARROW": (input) => input == '=>',
	"LPAREN": (input) => input == '(',
	"RPAREN": (input) => input == ')',
	"LBRACE": (input) => input == '{',
	"RBRACE": (input) => input == '}',
	"BAR": (input) => input == '|',
	"COMMA": (input) => input == ',',
	"SEMICOLON": (input) => input == ';',
	"COLON": (input) => input == ':',
	"BACKTICK": (input) => input == '`',
	"DOUBLEQUOTE": (input) => input == '"',
	"QUOTE": (input) => input == '\'',
	"DOT": (input) => input == '.',
	"DECLARATOR": (input) => input == '$',
	"NUMBER": (input) => /^[0-9]+$/.test(input),
	"LETTER": (input) => /^[a-zA-Z]+$/.test(input),
	"WHITESPACE": (input) => !/\S/.test(input),
	"UNRECOGNIZED": (input) => true,
};

const reserved = {
	kathan: "arguments",
	ruko: "await",
	viraam: "break",
	paks: "case",
	parantu: "catch",
	sangrah: "class",
	atal: "const",
	pravrtt: "continue",
	vishleshak: "debugger",
	hatao: "delete",
	karo: "do",
	athva: "else",
	vistaar: "extends",
	asatya: "false",
	antatah: "finally",
	chakra: "for",
	sutra: "function",
	jao: "goto",
	agar: "if",
	me: "in",
	kastrot: "instanceof",
	mana: "let",
	nava: "new",
	naganya: "null",
	samanya: "public",
	fal: "return",
	nirdesa: "switch",
	yah: "this",
	dosa: "throw",
	satya: "true",
	prayatn: "try",
	prakaar: "typeof",
	jabtak: "while",
	anay: "yield",
	dikhao: "dikhao"
};

module.exports = {
	tokenList,
	reserved,
};