name: Vedic Release CICD

on:
    workflow_dispatch:
        inputs:
            vesion:
                description: Version
                required: true
            prerelease:
                description: Prerelease
                required: true
                type: boolean

jobs:
    Build-Windows:
        name: "Build release for Windows"
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  profile: default
                  toolchain: stable
                  target: x86_64-pc-windows-msvc

            - name: Build binary
              shell: pwsh
              run: cicd/build_windows.ps1

            - name: Upload release
              uses: actions/upload-artifact@v4
              with:
                  name: windows
                  path: release_windows/*

    Build-Mac:
        name: "Build release for MacOS"
        runs-on: macos-latest # macos-11.0

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  profile: default
                  toolchain: stable
                  target: x86_64-apple-darwin

            - name: Build binary
              shell: bash
              run: bash cicd/build_mac.sh

            - name: Upload release
              uses: actions/upload-artifact@v4
              with:
                  name: mac
                  path: release_mac/*

    Build-Linux:
        name: "Build release for Linux"
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  profile: default
                  toolchain: stable
                  target: x86_64-unknown-linux-gnu

            - name: Build Linux
              shell: bash
              run: bash cicd/build_linux.sh

            - name: Upload release
              uses: actions/upload-artifact@v4
              with:
                  name: linux
                  path: release_linux/*

    Build-Android:
        name: "Build release for Android"
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  profile: default
                  toolchain: stable

            - name: Build Android binaries
              shell: bash
              run: bash cicd/build_android.sh

            - name: Upload release
              uses: actions/upload-artifact@v4
              with:
                  name: android
                  path: release_android/*              

    Release:
        needs: [Build-Windows, Build-Mac, Build-Linux, Build-Android]
        runs-on: ubuntu-latest

        steps:
            - name: Download release windows
              uses: actions/download-artifact@v5
              with:
                  name: windows
                  path: release_windows

            - name: Download release mac
              uses: actions/download-artifact@v5
              with:
                  name: mac
                  path: release_mac

            - name: Download release linux
              uses: actions/download-artifact@v5
              with:
                  name: linux
                  path: release_linux

            - name: Download release android
              uses: actions/download-artifact@v5
              with:
                  name: android
                  path: release_android

            - name: Generate SHA256 checksums
              run: |
                  sha256sum release_windows/* >> sha256sums.txt
                  sha256sum release_linux/* >> sha256sums.txt
                  sha256sum release_mac/* >> sha256sums.txt
                  sha256sum release_android/* >> sha256sums.txt

            - name: Publish
              uses: softprops/action-gh-release@v2
              with:
                  name: Vedic ${{ github.event.inputs.vesion }}
                  tag_name: v${{ github.event.inputs.vesion }}
                  prerelease: ${{ github.event.inputs.prerelease }}
                  token: ${{ secrets.GITHUB_TOKEN }}
                  generate_release_notes: true
                  draft: true
                  files: |
                      release_windows/*
                      release_linux/*
                      release_mac/*
                      release_android/*
                      sha256sums.txt
