name: Vedic Devlopment Testing

on:
    pull_request:
        branches: ["test"]
    workflow_dispatch:

env:
    CARGO_TERM_COLOR: always

jobs:
    Test:
        runs-on: ubuntu-latest

        steps:
            - name: check out branch
              uses: actions/checkout@v4

            - name: Build & Test
              run: python tools -bt
